DEV10265 - Adding region data in all integration (CI,SI,AJ)
EDP-Tiket/Workday pull request #127
Opened 2023-09-27 07:39 UTC by wahyu-di

Need to adding column region in all integration :
- customer invoice
- customer invoice adjustment (new integration)
- supplier invoice
- supplier invoice adjustment (new integration)
- accounting journal - INT011 need to adding column region in solver data as well format reference id region: region name BE_Region

2023-09-28 03:08 UTC, Rizki-H requested changes
Need to remove unnecessary query

2023-09-29 02:29 UTC, wahyu-di commented on Production/refund_raw.sql
> +  -- combine
Done update @Rizki-H, please check again.

2023-09-30 00:14 UTC, Rizki-H approved these changes
LGTM

2023-10-01 05:37 UTC, anggianggara commented
reviewed & approved

2023-10-01 05:37 UTC, merged