Changes format region ID
EDP-Tiket/Workday pull request #129
Opened 2023-10-10 04:48 UTC by wahyu-di

Changes format region ID from order__tixhotel

2023-10-10 08:54 UTC, Rizki-H requested changes

2023-10-10 08:54 UTC, Rizki-H commented on Production/customer_invoice_raw_part_2.sql
> +    -- left join dap on ott.hotel_provinceid = dap.region_id
We can delete this comment if it is no longer used

2023-10-10 09:00 UTC, wahyu-di commented on Production/customer_invoice_raw_part_2.sql
> +    -- left join dap on ott.hotel_provinceid = dap.region_id
sorry I forgot, Done updating. Please check again.

2023-10-11 11:13 UTC, Rizki-H approved these changes
LGTM

2023-10-11 11:31 UTC, merged