Adding type customer b2b corporate to type employee and instant
EDP-Tiket/Workday pull request #82
Opened 2023-03-29 10:32 UTC by wahyu-di

DEV10134 - Adding type customer b2b corporate to type employee and instant

2023-03-29 10:34 UTC, wahyu-di commented
DEV10134 - Adding type customer b2b corporate to type employee and instant

2023-03-30 02:30 UTC, Rizki-H requested changes
Please update the local branch first

2023-03-31 03:36 UTC, Rizki-H requested changes
Need some minor changes

2023-03-31 03:36 UTC, Rizki-H commented on Production/customer_invoice_raw_part_1.sql
> +    , split(from_email,'@') [offset(1)] as email_domain
Please use safe_offset

2023-03-31 03:36 UTC, Rizki-H commented on Production/customer_invoice_raw_part_2.sql
> +          -- when date(payment_timestamp) <'2020-04-06' and o.corporate_flag is not null then o.business_id /* 2020 04 06 - additional request for B2B Corporate only payment source cash_onsite*/ /*20
Please use slash (/) & star (*) as a comment

2023-03-31 03:36 UTC, Rizki-H commented on Production/customer_invoice_raw_part_2.sql
> +          -- when date(payment_timestamp) <'2020-04-06' and o.corporate_flag is not null then 'B2B Corporate' /* 2020 04 06 - additional request for B2B Corporate only payment source cash_onsite*/
Please use slash (/) & star (*) as a comment

2023-03-31 03:36 UTC, Rizki-H commented on Production/supplier_invoice_raw_part_1.sql
> +    --     end as customer_reference_id
Please use slash (/) & star (*) as a comment

2023-03-31 04:37 UTC, Rizki-H approved these changes
LGTM

2023-03-31 04:43 UTC, anggianggara commented
approved

2023-03-31 04:43 UTC, merged